---
title: "Exploratory Analysis on the Effect of COVID-19 on GDP: Discussion"
author: "Ian Whaling 914014658, Samuel Becerra Martinez 914309570, Esmeralda Buenrostro 915430778, Ryan Truong 916857334, Team ID: 9"
date: "March 10, 2021"
output:
  html_document:
    df_print: paged
    number_sections: yes
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H')
```

***


# Overall impression

This report is primarily focused on the differences between countries' ability to recover from the initial negative economic associations that came with COVID-19. It utilized the overall wealth of a country along with the proportion of the population with COVID-19 infections to find this difference in recovery. To gauge this economic recovery from COVID-19, the data was broken up into fiscal quarters, and specifically utilized Q2, which was the quarter where the initial associations of Covid-19 economy were first seen and Q3, which was the quarter where the economy began to recover. There were 3 datasets used: the WHO dataset with total daily numbers of infections/deaths per country, the change in GDP dataset which gave the percentage change in GDP from Q2 to Q3 for each country, and the GDP per capita dataset which gave 2019 GDP per capita for each country. An ANOVA model with no interaction effects was used to explain the difference in the percentage change in GDP in Q3 between countries. The population infected with COVID-19 was split into levels: [1 - Lowest, 2 - Moderate, 3 - Highest], and GDP per capita was also split: [1 - Poor, 2 - Moderate, 3 - Wealthy]. The statistical significance of these differences between percentage change in GDP between countries was measured and diagnostic tests were performed to measure errors. It found no errors and a Kruskal-Wallis test was used to test assumptions across the groups, and found no significant difference. Ultimately, the report found that the proportion of the population infected with COVID-19 and GDP per capita were not able to explain the variation observed in percentage GDP change in Q3 between each country. This meant that economic recovery in Q3 seemed to be consistent throughout the countries observed, likely due to the similar wealth that these countries exhibit. Some caveats included that developing countries did update GDP as frequently and lag behind on these statistics, so many poorer countries were not included which could be a reason for these findings.

T

# Major comments 

* Add descriptive/supporting analysis in the background. What have other studies shown? This could be a good addition because it can show what other studies have found on economic activity and Covid-19.
* Take the log: Maybe include a country's new cases per quarter, calculate the deaths per quarter or use case mortality rates
* Delve deeper into which factor is associated with which. Could economic recovery be playing a factor on Covid-19 cases? Why is this not the case? Explain.

1. The conclusion could use more explanation when it comes to the results. The report states, “We determine that the proportion of the population infected with COVID-19 and GDP per capita were not explicable in the variation observed in percentage GDP change in quarter 3 between each country.” Although the conclusion provides possible explanations as to why there is a lack of association between the percentage change in GDP and the two variables, it only focuses on the lack of up-to-date information on GDP. Rather than just concluding that there is a lack of up-to-date information or missing information, there should be a more thorough explanation for this conclusion that draws from real-word explanations or scenarios. There can be explanations for this conclusion, such as confounding variables, which can be a result of different policies set forth or any other factors specific to a certain country or geographic region. 

2. The two-factor ANOVA model produced in the inferential analysis should include interaction terms. The interaction term examines the effects of levels of one factor on the levels of the other factor, by excluding it from the analysis the question of interaction between COVID-19 infections and GDP per capita for each country is unresolved. If the interaction is non-significant it should be reported and discussed, if the interaction is significant the conclusion of the report should be changed to reflect this.

3. The descriptive analysis should be more reflective of the resulting statistical model explored in the inferential analysis. In other words, the descriptive analysis should lead up to the relation of GDP change to COVID-19 cases and GDP per capita. Graphs visualizing the relationship between each variable in the following model should be present, for example. Also, some of the data analyzed in the descriptive analysis, such as deaths, is not statistically relevant to the model and should probably be excluded unless it is explored further. 

4. There were a few instances where the word ‘impact’ was used, mainly in the context of describing how Covid-19 had an ‘impact’ on economic activity due to proportion of the population with COVID-19 infections and relative wealth of a nation. However, there should not be any causal statements made in the project unless they feel very confident about this causal inference. If no causal inference can be made, we can only conclude that there are associations between the two variables. This is because there may be other factors that can contribute to this change in economic activity that weren't included in the original model such as lifestyle or transportation. 

5. The introduction could go into more detail regarding the context of the time period explored in the data analysis, quarter 3. The third quarter of 2020 was remarked with almost universal economic recovery due to the adjustments and relaxing of regulations made following the sudden stipulations applied to commerce for initial lockdown/quarantine during quarter 2. This quarter was also when many countries saw their initial waves of COVID-19 cases, such as those in South-East Asia and Africa. The introduction should make note of distinctions of this quarter in the context of the ongoing pandemic, and they should be considered in the conclusion during discussions of confounders.


# Minor comments 

Visuals:

* In addition to what has been stated in Major Comments No. 3, graphs and visuals should be strategically selective and condensed. Having graphs and visuals can reveal great insights, but having too many graphs can cause confusion or redundancy. As an example, see Section 4.1.1 on the report. There are two graphs that are plotting the same thing. The only thing that differs them is removing a few points to zoom into the denser area, but the graph is not much more intuitive than the first.

Typos:

* 4.1.3 of Descriptive Analysis: ‘begining,' ‘differnce’ 
* 4.1.5 of Descriptive Analysis: ‘noticble’
* 4.4 of Descriptive Analysis: ‘here here’
* Inferential Analysis: ‘signicance,’ ‘signficantly,’ ‘signficant’
* Model Diagnostics: 'signicance,' 'signficant,' 'signficant'
* Various missing commas throughout the report
* 'gdp' is not fully capitalized as it should be many times throughout the report

Other:

* The output for some code is present beneath the Background with no context given.


# Questions to address during the final presentation

1. Is the interaction term significant or non-significant? If so, which interaction terms are significantly different and how does this change the conclusion?
2. What are some confounding variables that could explain why was there no significance observed?
3. How might the findings of this report apply to other quarters or time periods during the pandemic and what is the applicability of these findings to our current or future situation?
4. What are some other ideas that can be discussed to further explore the association of economy and COVID-19?
5. What could be some explanations for the uniform global recovery in GDP in Q3?
